# Generated by Django 5.2.17 on 2026-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_repurpose_equipment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
