# Generated by Django 5.2.17 on 2026-08-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(choices=[('SALE', 'Sale Checkout'), ('STOCK_PURCHASE', 'Stock Purchase'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('INITIAL_SETUP', 'Initial Inventory Setup')], db_index=True, max_length=30)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'created_at'], name='inventory_i_variant_b826d6_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_0d8590_idx')],
            },
        ),
    ]
