# Generated by Django 6.0.7 on 2026-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(default='Al-Amaan Pharmacy', max_length=150)),
                ('phone', models.CharField(default='+234 800 000 0000', max_length=50)),
                ('email', models.EmailField(default='contact@alamaanpharmacy.com', max_length=254)),
                ('address', models.TextField(default='Suite 12, Commercial Plaza, Kano, Nigeria')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('business_description', models.TextField(blank=True, default='Licensed Retail Pharmacy & Healthcare Provider')),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('show_decimals', models.BooleanField(default=True)),
                ('allow_walking_sales', models.BooleanField(default=True)),
                ('allow_credit_sales', models.BooleanField(default=True)),
                ('require_customer_for_credit', models.BooleanField(default=True)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('receipt_footer', models.TextField(default='Thank you for your patronage. Get well soon!')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
